Make test great again
youpin-city/youpin-api pull request #137
Opened 2016-11-21 10:16 UTC by supasate

- [x] Set NODE_ENV=test automatically
- [x] Use different port
- [x] Hide server's log
- [x] Hide eslint warning

2016-11-21 13:30 UTC, parnurzeal requested changes

2016-11-21 13:30 UTC, parnurzeal commented on test/.eslintrc.yml
> -extends: airbnb
we don't use airbnb format anymore?

2016-11-21 13:30 UTC, parnurzeal commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
little bit comment, plz.

2016-11-21 13:30 UTC, parnurzeal commented on config/default.template.json
> +    "filename": "api-log.txt"
api.log? how do we manage old log with different date?

2016-11-21 13:30 UTC, parnurzeal commented on test/.eslintrc.yml
> -  - react
What is this?

2016-11-21 13:30 UTC, parnurzeal commented on test/.eslintrc.yml
> -  node: true
?

2016-11-21 16:21 UTC, supasate commented on test/.eslintrc.yml
> -extends: airbnb
I just remember that it can use the outer .eslintrc.ymn instead. This file just override some rules.

2016-11-21 16:22 UTC, supasate commented on test/.eslintrc.yml
> -  - react
In the previous setting, I used `extends: airbnb` which depends on `react` plugins.

2016-11-21 16:27 UTC, supasate commented on test/.eslintrc.yml
> -  node: true
`env` setting is for letting eslint ignore global variables of each environment. `node` is to ignore `module`, `process`, etc.

The `airbnb/base` in outer .eslintrc has already done that for us (https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/node.js).

2016-11-21 16:29 UTC, supasate commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
If we are not in a `test` environment, create a logs folder if it doesn't exist. Then, tell winston to write log to a file.

2016-11-21 16:32 UTC, supasate commented on config/default.template.json
> +    "filename": "api-log.txt"
Currently, it appends datetime in each record in the log file.

To separate daily log files, we may need [this package](https://github.com/winstonjs/winston-daily-rotate-file). Anyway, will do it as a separated PR.

2016-11-21 16:34 UTC, supasate commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
Else, remove displaying error to console.

2016-11-22 14:08 UTC, parnurzeal commented on test/.eslintrc.yml
> -extends: airbnb
Not sure what the .eslintrc.ymn is.

2016-11-22 14:09 UTC, parnurzeal commented on test/.eslintrc.yml
> -extends: airbnb
Oh ok... .eslint.yml lol. Nvm on this.

2016-11-22 14:10 UTC, parnurzeal commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
I understand that after reading the code but I mean let's put a little bit comment in the code. Since it is not obvious after reading through the code.

2016-11-22 14:12 UTC, supasate commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
Oh. Sure.

2016-11-22 14:14 UTC, parnurzeal commented on config/default.template.json
> +    "filename": "api-log.txt"
again, please rename api-log.txt -> api.log

2016-11-22 14:21 UTC, supasate commented on src/middleware/logger.js
> +  if (process.env.NODE_ENV !== 'test') {
@parnurzeal Done in new commit

2016-11-22 14:23 UTC, supasate commented on config/default.template.json
> +    "filename": "api-log.txt"
Done

2016-11-22 14:45 UTC, parnurzeal commented on src/middleware/logger.js
> +    // In test environment, do not print log to console
Actually, why don't we print log to console if it's a test?

2016-11-22 15:06 UTC, supasate commented on src/middleware/logger.js
> +    // In test environment, do not print log to console
It intervenes the mocha output and makes it hard to read (and annoy also). 

In `test` environment (not `dev` environment), we just want to compare the actual outcome with expected outcome; no need logging. 

Anyway, if we would like to log something out to console, we still can use console.log instead.

2016-11-22 15:19 UTC, parnurzeal commented
LGTM.

2016-11-22 15:20 UTC, parnurzeal approved these changes

2016-11-22 15:21 UTC, supasate commented
Sure!

2016-11-22 15:27 UTC, supasate commented
Done

2016-11-22 16:06 UTC, merged