More info. and better content in email notification
youpin-city/youpin-api pull request #297
Opened 2017-05-10 11:21 UTC by parnurzeal

2017-05-12 02:55 UTC, rapee commented on package.json
> +    "grpc": "^1.3.1",
`grpc` is included but never used.

2017-05-12 11:45 UTC, parnurzeal commented on package.json
> +    "grpc": "^1.3.1",
OK will delete.

2017-05-12 15:17 UTC, supasate commented on src/services/pin-state-transition/hooks/prepare-activity-log.js
> +          previousValues.push(assignedDepartmentObject);
Do we need to upgrade data in database from id to object?

2017-05-12 15:18 UTC, supasate commented on src/utils/send-mail-notification.js
> +    const newUpdatedValues = [];
a new line after variable declaration

2017-05-12 15:18 UTC, supasate commented on src/utils/send-mail-notification.js
> +      let updatedValue = ctx.updatedValues[idx];
a new line after variable declaration

2017-05-12 15:21 UTC, supasate commented on src/utils/send-mail-notification.js
>    const template = new EmailTemplate(templateDir);
nit: a new line after variable declaration

2017-05-12 15:26 UTC, supasate commented on test/services/pin-state-transition/hooks/prepare-activity-log.test.js
> +const DEPARTMENT_GENERAL_OBJECT = require('../../../fixtures/departments')[1];
This will cause flaky test if the order is changed in the future. Use `filter` with ObjectId or name instead.

2017-05-12 15:27 UTC, supasate commented on test/services/pin-state-transition/hooks/prepare-activity-log.test.js
> +      const actualLogInfo = mockHook.data.logInfo;
Why do we have to compare field by field manually?
The old one doesn't compare nested fields?

2017-05-12 15:28 UTC, supasate requested changes
Overall LGTM. Have some nits.

2017-05-13 08:46 UTC, parnurzeal commented on test/services/pin-state-transition/hooks/prepare-activity-log.test.js
> +const DEPARTMENT_GENERAL_OBJECT = require('../../../fixtures/departments')[1];
Reverted it back.

2017-05-13 08:46 UTC, parnurzeal commented on src/utils/send-mail-notification.js
> +    const newUpdatedValues = [];
Done

2017-05-13 08:46 UTC, parnurzeal commented on src/utils/send-mail-notification.js
> +      let updatedValue = ctx.updatedValues[idx];
Done

2017-05-13 08:46 UTC, parnurzeal commented on src/utils/send-mail-notification.js
>    const template = new EmailTemplate(templateDir);
Done.

2017-05-13 08:46 UTC, parnurzeal commented on test/services/pin-state-transition/hooks/prepare-activity-log.test.js
> +      const actualLogInfo = mockHook.data.logInfo;
The object from hook is huge and have more info than we can mock.
But please nvm on this. I changed the approach. Nothing will affect the activity log model.

2017-05-13 08:46 UTC, parnurzeal commented on src/services/pin-state-transition/hooks/prepare-activity-log.js
> +          previousValues.push(assignedDepartmentObject);
You are totally right. This is complicated.
I changed the approach to populate everything inside email-noti function instead.
PTAL @supasate @rapee

2017-05-13 08:46 UTC, parnurzeal commented on package.json
> +    "grpc": "^1.3.1",
DONE.

2017-05-14 06:18 UTC, parnurzeal commented
If new implementation LGTY, before merging, please help squashing to one single commit.

2017-05-14 16:55 UTC, supasate commented
LGTM!

2017-05-14 16:55 UTC, merged